* Burninator Ra
	- Power: Deal all targets 50 fire damage
* Lucky Setback
	- Power: Deal a random number of random targets a random amount of a random type of damage. The damage dealt will be between 1 and the total number of targets. Randomly add or remove that many tokens from the luck pool.
* America's Weakest Legacy
	- 1 HP
	- Power: Deal 0 damage to 1 target.
* America's Youngest Legacy
	- 10 HP
	- Power: Deal 1 sonic damage to each target. Targets damaged this way deal themselves 1 psychic damage.
* Tree Hugger Akash
	- Power: Play X cards from the environment deck, where X is the number of cards in the environment deck.
* Time Loop Chronoranger
	- Power: Play a card. Use a power. Draw a card.
* The unnaturalist
  - Power: Search your hand, deck, and discard pile for all forms and play them. Use a power. Use a power. Use a power.
* Absolute 1
  - deal 1 target 1 cold damage. 1 Hero may play 1 card. 1 hero may use 1 power. 1 hero may draw 1 card. 1 target gains 1 HP. Destroy 1 environment card.
* Chando
	- Wendy
	- Flower tummy wendy
	- Rainbow tummy wendy
	- Benny
	- Zozo
	- Brina
	- Caparine
	- Dante
	- Big squish
	- Big foot club
	- Mushroom A
	- Mushroom B
	- Mushroom C
	- Frog squad
	- Mushroom squd
	- Georgie
	- Maisy
	-
	-
	-
	-
	-
	-
	-
	-
	-
	-
	-
	-
	-
	-
	-
	-
	-
	-
	-
	-
	-
	-
	-
